# Generated by Django 5.2.4 on 2025-07-26 10:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
